### ISSUE TITLE
Describe approach for setting up Mondoo actions for forks

### ISSUE THREAD

**Issue by imilchev** [mondoohq/actions#48]
Currently, if I follow the docs and setup the Mondoo actions in a repo they work fine for the repo but they fail for forks. This is caused by the fact that forks cannot access the secret that contains the Mondoo service account. We should figure out a way to configure the actions for forks and document it.

For reference: https://github.com/podkrepi-bg/api/actions/runs/3629968259/jobs/6122775363

**Comment by chris-rock** [comment]
If I understand the referenced repo correct, it is not a fork. Can you explain what you mean by forks?
