### ISSUE TITLE
Actions need an upgrade to v9

### ISSUE THREAD

**Issue by czunker** [mondoohq/actions#71]
**Is your feature request related to a problem? Please describe.**
Actions are still using cnspec v8.

**Describe the solution you'd like**
Upgrade to cnspec v9.

**Describe alternatives you've considered**
Keep v8. Not really an option.

**Comment by czunker** [comment]
First easy step is to bump the tag from v8 to v9.

But this will result in the actions downloading the needed provider each time they are executed. The better solution would be to have custom images for the different actions where the needed providers are pre-installed.

Next step would be to automatically update these images each time a new provider or cnspec version is released.

Perhaps we can take some parts for this from the mondoo-operator repo. There we also have a custom image.

**Comment by imilchev** [comment]
fixed
